"""Auto-generated cpp CLI/library scaffolder (E1 language roots).

Registered in generation/__init__.py:first_party_scaffolds as 'cpp-cli' and
'cpp-lib'. Follows the same contract as cargo_cli / npm_commander_cli.
"""
from __future__ import annotations

import re
from pathlib import Path

from ..recipes import ProviderView, RecipeError, ScaffoldResult, run_command

FILES_CLI = {'CMakeLists.txt': 'cmake_minimum_required(VERSION 3.28)\nproject(__PKG__ CXX)\nadd_executable(__PKG__ src/main.cpp)\nenable_testing()\n', 'src/main.cpp': '// PURPOSE: __PURPOSE__\n#include <iostream>\n\nint main() {\n  std::cout << "Project scaffold ready. Implement domain behavior through the coding-agent workflow." << std::endl;\n  return 0;\n}\n'}
FILES_LIB = {'CMakeLists.txt': 'cmake_minimum_required(VERSION 3.28)\nproject(__PKG__ CXX)\nadd_library(__PKG__ src/lib.cpp)\n', 'src/lib.cpp': '// PURPOSE: __PURPOSE__\n#include "__PKG__.h"\n\nconst char* scaffoldStatus() { return "__PKG__ scaffold ready"; }\n', 'src/__PKG__.h': '#ifndef __PKG___H\n#define __PKG___H\nconst char* scaffoldStatus();\n#endif\n'}
INIT_CLI = ['-S', '.', '-B', 'build']
INIT_LIB = ['-S', '.', '-B', 'build']


def _fill_content(content: str, pkg: str, purpose: str) -> str:
    return content.replace("__PKG__", pkg).replace("__PURPOSE__", purpose)


def _write_harness_context(project_root: Path, pkg: str, purpose: str) -> None:
    # E4: emit the canonical harness context file so Codex/Claude/Gemini skill
    # adapters can consume the generated project without extra setup.
    (project_root / "AGENTS.md").write_text(
        "# " + pkg + "\n\n" + purpose + "\n\nGenerated by Project Factory. "
        "Canonical harness adapters (codex/claude/gemini) read AGENTS.md.\n",
        encoding="utf-8",
    )


def _pkg(project_name: str) -> str:
    return re.sub(r"[^a-zA-Z0-9]", "", project_name) or "demo"


def _scaffold(project_root: Path, staging_root: Path, project_name: str, purpose: str,
              files: dict, init_cmd, provider: ProviderView, recipe: str) -> ScaffoldResult:
    pkg = _pkg(project_name)
    project_root.mkdir(parents=True, exist_ok=False)
    if init_cmd is not None:
        filled = [pkg if a == "__PKG__" else a for a in init_cmd]
        run_command([provider.executable, *filled], project_root, timeout=600)
        for rel, content in files.items():
            p = project_root / rel
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(_fill_content(content, pkg, purpose), encoding="utf-8")
    _write_harness_context(project_root, pkg, purpose)
    return ScaffoldResult(
        command_result={"recipe": recipe, "provider": provider.executable},
        layout={"source": "src/" if files else ".", "packaging": "manifest"},
    )


def scaffold_cpp_cli(recipe: str, provider: ProviderView, project_name: str, project_root: Path,
                    staging_root: Path, purpose: str) -> ScaffoldResult:
    if recipe != "cpp-cli":
        raise RecipeError(f"Unsupported cpp CLI scaffold recipe: {recipe}")
    return _scaffold(project_root, staging_root, project_name, purpose, FILES_CLI, INIT_CLI, provider, recipe)


def scaffold_cpp_lib(recipe: str, provider: ProviderView, project_name: str, project_root: Path,
                    staging_root: Path, purpose: str) -> ScaffoldResult:
    if recipe != "cpp-lib":
        raise RecipeError(f"Unsupported cpp library scaffold recipe: {recipe}")
    return _scaffold(project_root, staging_root, project_name, purpose, FILES_LIB, INIT_LIB, provider, recipe)
