"""Auto-generated dart CLI/library scaffolder (E1 language roots).

Registered in generation/__init__.py:first_party_scaffolds as 'dart-cli' and
'dart-lib'. Follows the same contract as cargo_cli / npm_commander_cli.
"""
from __future__ import annotations

import re
from pathlib import Path

from ..recipes import ProviderView, RecipeError, ScaffoldResult, run_command

FILES_CLI = {'bin/__PKG__.dart': '// PURPOSE: __PURPOSE__\nvoid main(List<String> args) {\n  print("Project scaffold ready. Implement domain behavior through the coding-agent workflow.");\n}\n', 'lib/__PKG__.dart': '// PURPOSE: __PURPOSE__\nString scaffoldStatus() => "__PKG__ scaffold ready";\n', 'pubspec.yaml': 'name: __PKG__\ndescription: __PURPOSE__\nversion: 0.1.0\nenvironment:\n  sdk: ">=3.0.0 <4.0.0"\ndev_dependencies:\n  test: ^1.24.0\n'}
FILES_LIB = {'lib/__PKG__.dart': '// PURPOSE: __PURPOSE__\nString scaffoldStatus() => "__PKG__ library scaffold ready";\n', 'pubspec.yaml': 'name: __PKG__\ndescription: __PURPOSE__\nversion: 0.1.0\nenvironment:\n  sdk: ">=3.0.0 <4.0.0"\ndev_dependencies:\n  test: ^1.24.0\n'}
INIT_CLI = None
INIT_LIB = None


def _fill_content(content: str, pkg: str, purpose: str) -> str:
    return content.replace("__PKG__", pkg).replace("__PURPOSE__", purpose)


def _write_harness_context(project_root: Path, pkg: str, purpose: str) -> None:
    # E4: emit the canonical harness context file so Codex/Claude/Gemini skill
    # adapters can consume the generated project without extra setup.
    (project_root / "AGENTS.md").write_text(
        "# " + pkg + "\n\n" + purpose + "\n\nGenerated by Project Factory. "
        "Canonical harness adapters (codex/claude/gemini) read AGENTS.md.\n",
        encoding="utf-8",
    )


def _pkg(project_name: str) -> str:
    return re.sub(r"[^a-z0-9_]+", "_", project_name.lower()).strip("_") or "demo"


def _scaffold(project_root: Path, staging_root: Path, project_name: str, purpose: str,
              files: dict, init_cmd, provider: ProviderView, recipe: str) -> ScaffoldResult:
    pkg = _pkg(project_name)
    project_root.mkdir(parents=True, exist_ok=False)
    if init_cmd is not None:
        filled = [pkg if a == "__PKG__" else a for a in init_cmd]
        run_command([provider.executable, *filled], project_root, timeout=600)
        for rel, content in files.items():
            p = project_root / rel
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(_fill_content(content, pkg, purpose), encoding="utf-8")
    _write_harness_context(project_root, pkg, purpose)
    return ScaffoldResult(
        command_result={"recipe": recipe, "provider": provider.executable},
        layout={"source": "src/" if files else ".", "packaging": "manifest"},
    )


def scaffold_dart_cli(recipe: str, provider: ProviderView, project_name: str, project_root: Path,
                    staging_root: Path, purpose: str) -> ScaffoldResult:
    if recipe != "dart-cli":
        raise RecipeError(f"Unsupported dart CLI scaffold recipe: {recipe}")
    return _scaffold(project_root, staging_root, project_name, purpose, FILES_CLI, INIT_CLI, provider, recipe)


def scaffold_dart_lib(recipe: str, provider: ProviderView, project_name: str, project_root: Path,
                    staging_root: Path, purpose: str) -> ScaffoldResult:
    if recipe != "dart-lib":
        raise RecipeError(f"Unsupported dart library scaffold recipe: {recipe}")
    return _scaffold(project_root, staging_root, project_name, purpose, FILES_LIB, INIT_LIB, provider, recipe)
