"""Auto-generated mobile-app / game / userscript scaffolders (E3).

Registered in generation/__init__.py:first_party_scaffolds per MODELS keys.
"""
from __future__ import annotations

import re
from pathlib import Path

from ..recipes import ProviderView, RecipeError, ScaffoldResult, run_command

MODELS = {
    "flutter-mobile": dict(files={'pubspec.yaml': 'name: __PKG__\ndescription: __PURPOSE__\nversion: 0.1.0\nenvironment:\n  sdk: ">=3.0.0 <4.0.0"\n', 'lib/main.dart': '// PURPOSE: __PURPOSE__\nvoid main() {\n  print("Project scaffold ready. Implement domain behavior through the coding-agent workflow.");\n}\n'},
                 init=None,
                 build=['flutter', 'analyze'],
                 test=None,
                 artifacts=['pubspec.lock'],
                 family='mobile-app', work='mobile-app', tech='flutter',
                 provider='flutter', recipe='mobile-flutter', rt='dart'),
    "kotlin-mobile": dict(files={'build.gradle.kts': 'plugins {\n    id("com.android.application")\n    kotlin("android")\n}\n', 'src/main/kotlin/App.kt': '// PURPOSE: __PURPOSE__\npackage app\n\nfun main() {\n    println("Project scaffold ready. Implement domain behavior through the coding-agent workflow.")\n}\n', 'settings.gradle.kts': 'rootProject.name = "__PKG__"\n'},
                 init=None,
                 build=['gradle', 'assembleDebug', '--offline'],
                 test=None,
                 artifacts=['build/outputs/*'],
                 family='mobile-app', work='mobile-app', tech='kotlin',
                 provider='kotlin', recipe='mobile-kotlin', rt='kotlin'),
    "swift-mobile": dict(files={},
                 init=['package', 'init', '--type', 'executable'],
                 build=['swift', 'build'],
                 test=['swift', 'test'],
                 artifacts=['.build/debug/*'],
                 family='mobile-app', work='mobile-app', tech='swift',
                 provider='swift', recipe='mobile-swift', rt='swift'),
    "bevy-game": dict(files={'Cargo.toml': '[package]\nname = "__PKG__"\nversion = "0.1.0"\nedition = "2021"\n\n[dependencies]\nbevy = "0.13"\n', 'src/main.rs': '// PURPOSE: __PURPOSE__\nuse bevy::prelude::*;\n\nfn main() {\n    App::new().add_plugins(DefaultPlugins).run();\n}\n'},
                 init=None,
                 build=['cargo', 'build', '--offline'],
                 test=['cargo', 'test', '--offline'],
                 artifacts=['target/debug/*'],
                 family='game', work='game', tech='rust,bevy',
                 provider='cargo', recipe='game-bevy', rt='rust'),
    "godot-game": dict(files={'project.godot': '; Engine configuration for __PKG__\n; PURPOSE: __PURPOSE__\n[application]\n\nconfig/name="__PKG__"\n', 'main.gd': '# PURPOSE: __PURPOSE__\nextends Node\n\nfunc _ready():\n\tprint("Project scaffold ready. Implement domain behavior through the coding-agent workflow.")\n'},
                 init=None,
                 build=['godot', '--headless', '--quit'],
                 test=None,
                 artifacts=['.godot/*'],
                 family='game', work='game', tech='godot',
                 provider='godot', recipe='game-godot', rt='gdscript'),
    "typescript-userscript": dict(files={'package.json': '{\n  "name": "__PKG__",\n  "version": "0.1.0",\n  "description": "__PURPOSE__",\n  "private": true,\n  "type": "module"\n}\n', 'src/userscript.ts': '// PURPOSE: __PURPOSE__\n// Tampermonkey / Violentmonkey userscript bootstrap.\n// @license MIT\n'},
                 init=None,
                 build=['npm', 'run', 'build'],
                 test=None,
                 artifacts=['dist/*'],
                 family='userscript', work='userscript', tech='typescript',
                 provider='npm', recipe='userscript-ts', rt='node'),
}


def _write_harness_context(project_root: Path, pkg: str, purpose: str) -> None:
    # E4: emit the canonical harness context file so Codex/Claude/Gemini skill
    # adapters can consume the generated project without extra setup.
    (project_root / "AGENTS.md").write_text(
        "# " + pkg + "\n\n" + purpose + "\n\nGenerated by Project Factory. "
        "Canonical harness adapters (codex/claude/gemini) read AGENTS.md.\n",
        encoding="utf-8",
    )


def _scaffold_model(recipe: str, provider: ProviderView, project_name: str, project_root: Path,
                    staging_root: Path, purpose: str) -> ScaffoldResult:
    spec = MODELS.get(recipe)
    if spec is None:
        raise RecipeError(f"Unsupported E3 scaffold recipe: {recipe}")
    pkg = re.sub(r"[^a-z0-9_]+", "_", project_name.lower()).strip("_") or "demo"
    project_root.mkdir(parents=True, exist_ok=False)
    if spec["init"] is None:
        for rel, content in spec["files"].items():
            p = project_root / rel
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(content.replace("__PKG__", pkg).replace("__PURPOSE__", purpose), encoding="utf-8")
    else:
        filled = [pkg if a == "__PKG__" else a for a in spec["init"]]
        run_command([provider.executable, *filled], project_root, timeout=600)
        for rel, content in spec["files"].items():
            p = project_root / rel
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(content.replace("__PKG__", pkg).replace("__PURPOSE__", purpose), encoding="utf-8")
    _write_harness_context(project_root, pkg, purpose)
    return ScaffoldResult(
        command_result={"recipe": recipe, "provider": provider.executable},
        layout={"source": "src/" if spec["files"] else ".", "packaging": "manifest"},
    )


def scaffold_mobile_flutter(recipe, provider, project_name, project_root, staging_root, purpose):
    return _scaffold_model(recipe, provider, project_name, project_root, staging_root, purpose)


def scaffold_mobile_kotlin(recipe, provider, project_name, project_root, staging_root, purpose):
    return _scaffold_model(recipe, provider, project_name, project_root, staging_root, purpose)


def scaffold_mobile_swift(recipe, provider, project_name, project_root, staging_root, purpose):
    return _scaffold_model(recipe, provider, project_name, project_root, staging_root, purpose)


def scaffold_game_bevy(recipe, provider, project_name, project_root, staging_root, purpose):
    return _scaffold_model(recipe, provider, project_name, project_root, staging_root, purpose)


def scaffold_game_godot(recipe, provider, project_name, project_root, staging_root, purpose):
    return _scaffold_model(recipe, provider, project_name, project_root, staging_root, purpose)


def scaffold_userscript_ts(recipe, provider, project_name, project_root, staging_root, purpose):
    return _scaffold_model(recipe, provider, project_name, project_root, staging_root, purpose)
