"""Auto-generated r CLI/library scaffolder (E1 language roots).

Registered in generation/__init__.py:first_party_scaffolds as 'r-cli' and
'r-lib'. Follows the same contract as cargo_cli / npm_commander_cli.
"""
from __future__ import annotations

import re
from pathlib import Path

from ..recipes import ProviderView, RecipeError, ScaffoldResult, run_command

FILES_CLI = {'DESCRIPTION': 'Package: __PKG__\nTitle: __PURPOSE__\nVersion: 0.1.0\nDescription: Bootstrap scaffold for an R command-line tool.\nLicense: MIT + file LICENSE\n', 'R/__PKG__.R': '# PURPOSE: __PURPOSE__\nscaffold_status <- function() paste0("__PKG__ scaffold ready")\n', 'exec/__PKG__': '#!/usr/bin/env Rscript\nargs <- commandArgs(trailingOnly = TRUE)\nif ("--version" %in% args) { cat("0.1.0\\n"); quit() }\ncat("Project scaffold ready. Implement domain behavior through the coding-agent workflow.\\n")\n'}
FILES_LIB = {'DESCRIPTION': 'Package: __PKG__\nTitle: __PURPOSE__\nVersion: 0.1.0\nDescription: Bootstrap scaffold for an R library.\nLicense: MIT + file LICENSE\n', 'R/__PKG__.R': '# PURPOSE: __PURPOSE__\nscaffold_status <- function() paste0("__PKG__ library scaffold ready")\n'}
INIT_CLI = None
INIT_LIB = None


def _fill_content(content: str, pkg: str, purpose: str) -> str:
    return content.replace("__PKG__", pkg).replace("__PURPOSE__", purpose)


def _write_harness_context(project_root: Path, pkg: str, purpose: str) -> None:
    # E4: emit the canonical harness context file so Codex/Claude/Gemini skill
    # adapters can consume the generated project without extra setup.
    (project_root / "AGENTS.md").write_text(
        "# " + pkg + "\n\n" + purpose + "\n\nGenerated by Project Factory. "
        "Canonical harness adapters (codex/claude/gemini) read AGENTS.md.\n",
        encoding="utf-8",
    )


def _pkg(project_name: str) -> str:
    return re.sub(r"[^a-zA-Z0-9.]", "", project_name) or "demo"


def _scaffold(project_root: Path, staging_root: Path, project_name: str, purpose: str,
              files: dict, init_cmd, provider: ProviderView, recipe: str) -> ScaffoldResult:
    pkg = _pkg(project_name)
    project_root.mkdir(parents=True, exist_ok=False)
    if init_cmd is not None:
        filled = [pkg if a == "__PKG__" else a for a in init_cmd]
        run_command([provider.executable, *filled], project_root, timeout=600)
        for rel, content in files.items():
            p = project_root / rel
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(_fill_content(content, pkg, purpose), encoding="utf-8")
    _write_harness_context(project_root, pkg, purpose)
    return ScaffoldResult(
        command_result={"recipe": recipe, "provider": provider.executable},
        layout={"source": "src/" if files else ".", "packaging": "manifest"},
    )


def scaffold_r_cli(recipe: str, provider: ProviderView, project_name: str, project_root: Path,
                    staging_root: Path, purpose: str) -> ScaffoldResult:
    if recipe != "r-cli":
        raise RecipeError(f"Unsupported r CLI scaffold recipe: {recipe}")
    return _scaffold(project_root, staging_root, project_name, purpose, FILES_CLI, INIT_CLI, provider, recipe)


def scaffold_r_lib(recipe: str, provider: ProviderView, project_name: str, project_root: Path,
                    staging_root: Path, purpose: str) -> ScaffoldResult:
    if recipe != "r-lib":
        raise RecipeError(f"Unsupported r library scaffold recipe: {recipe}")
    return _scaffold(project_root, staging_root, project_name, purpose, FILES_LIB, INIT_LIB, provider, recipe)
