"""Official MCP Python SDK v2 body on the uv language root.

This is a generated-project plugin. The Factory does not become an MCP Host.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from ..recipes import (
    ProviderView,
    RecipeError,
    ScaffoldResult,
    _patch_python_pyproject,
    _python_package_name,
    run_command,
)


def _render_server(project_name: str, package_name: str, purpose: str) -> str:
    return f'''from __future__ import annotations

from mcp.server import MCPServer

PURPOSE = {purpose!r}

mcp = MCPServer({project_name!r})


@mcp.tool()
def echo_purpose() -> str:
    """Return the project purpose so a host can sanity-check this server."""
    return PURPOSE


@mcp.resource("scaffold://status")
def scaffold_status() -> str:
    """Static scaffold status for hosts that read resources."""
    return "mcp server scaffold ready"


@mcp.prompt()
def introduce() -> str:
    """User-invoked prompt describing this generated MCP server."""
    return (
        "This is a native MCP server generated by Project Factory. "
        f"Purpose: {{PURPOSE}}"
    )


def main() -> None:
    mcp.run()


if __name__ == "__main__":
    main()
'''


def _render_init() -> str:
    return '''from __future__ import annotations

from .server import main, mcp

__all__ = ["main", "mcp"]
'''


def _render_unittest(package_name: str) -> str:
    return f'''from __future__ import annotations

import asyncio
import unittest

from mcp import Client

from {package_name}.server import mcp


class McpServerSmokeTest(unittest.TestCase):
    def test_in_memory_tool_call(self) -> None:
        async def _run() -> None:
            async with Client(mcp, raise_exceptions=True) as client:
                result = await client.call_tool("echo_purpose", {{}})
                self.assertFalse(getattr(result, "is_error", False))
                self.assertTrue(result.content)
                self.assertTrue(str(result.content[0].text))

        asyncio.run(_run())

    def test_server_declares_tool_capability(self) -> None:
        async def _run() -> None:
            async with Client(mcp, raise_exceptions=True) as client:
                caps = client.server_capabilities.model_dump(exclude_none=True)
                self.assertIn("tools", caps)

        asyncio.run(_run())


if __name__ == "__main__":
    unittest.main()
'''


def _render_real_host_script(package_name: str) -> str:
    """Q4-③: developer-executed real-host smoke check (real STDIO, not the in-memory Client test)."""
    return f'''"""Q4-③: real-host smoke check for the generated MCP server.

Spawns the server over real STDIO and connects a real MCP client (not the in-memory
transport used by the unit test). Run with: `uv run python scripts/verify_real_host.py`.
"""
from __future__ import annotations

import asyncio
import sys

from mcp import ClientSession
from mcp.client.stdio import StdioServerParameters, stdio_client


async def _run() -> None:
    params = StdioServerParameters(command=sys.executable, args=["-m", "{package_name}.server"])
    async with stdio_client(params) as (read, write):
        async with ClientSession(read, write) as session:
            await session.initialize()
            result = await session.call_tool("echo_purpose", {{}})
            assert result.content, "echo_purpose returned no content"
            text = str(result.content[0].text)
            assert text, "echo_purpose returned empty text"
            print("REAL HOST OK:", text)


if __name__ == "__main__":
    asyncio.run(_run())
'''


def scaffold_uv_mcp_server(
    recipe: str,
    provider: ProviderView,
    project_name: str,
    project_root: Path,
    staging_root: Path,
    purpose: str,
) -> ScaffoldResult:
    if recipe != "uv-mcp-server":
        raise RecipeError(f"Unsupported MCP scaffold recipe: {recipe}")
    package_name = _python_package_name(project_name)
    scaffold = run_command(
        [
            provider.executable,
            "init",
            "--app",
            "--package",
            "--name",
            project_name,
            "--vcs",
            "none",
            "--no-pin-python",
            "--no-workspace",
            str(project_root),
        ],
        staging_root,
    )
    _patch_python_pyproject(project_root / "pyproject.toml", purpose)
    run_command([provider.executable, "add", "mcp"], project_root, timeout=600)
    package_dir = project_root / "src" / package_name
    package_dir.mkdir(parents=True, exist_ok=True)
    (package_dir / "server.py").write_text(
        _render_server(project_name, package_name, purpose), encoding="utf-8"
    )
    (package_dir / "__init__.py").write_text(_render_init(), encoding="utf-8")
    tests = project_root / "tests"
    tests.mkdir(parents=True, exist_ok=True)
    (tests / "test_smoke.py").write_text(_render_unittest(package_name), encoding="utf-8")
    scripts = project_root / "scripts"
    scripts.mkdir(parents=True, exist_ok=True)
    (scripts / "verify_real_host.py").write_text(_render_real_host_script(package_name), encoding="utf-8")
    return ScaffoldResult(
        command_result=scaffold,
        layout={
            "source": f"src/{package_name}/",
            "server": f"src/{package_name}/server.py",
            "tests": "tests/",
            "scripts": "scripts/",
            "packaging": "pyproject.toml",
        },
    )
